version: '3.7'
services:
    back:
        container_name: hop
        build: .
        ports:
            - '3000:3000'
        restart: always
        depends_on:
            - mongo
    mongo:
        container_name: mongo
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${ROOT_DB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${ROOT_DB_PASSWORD}
            MONGO_INITDB_DATABASE: ${DB_NAME}
            MONGO_DB_USER: ${DB_USER}
            MONGO_DB_PASSWORD: ${DB_PASSWORD}
        restart: always
        volumes:
            - data-volume:/data/db
            - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
volumes:
    data-volume:
